AWSTemplateFormatVersion: "2010-09-09"
Description: Hello world

Resources:
  ArjanSecurityGroupIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId: !Ref ElvinSecurityGroup
      GroupId: !Ref ArjanSecurityGroup

  ElvinSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: lalala
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref ArjanSecurityGroup
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ArjanSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: lalala
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  
